# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8xGAGFSTz-hyggoamGOMKiE5QAd8FaN
"""

!pip install opencv-python matplotlib scikit-learn

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import seaborn as sns

"""Upload ZIP Dataset"""

from google.colab import files

uploaded = files.upload()

"""Extract ZIP File"""

import zipfile

zip_path = "archive (5).zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("dataset")

vitiligo_path = "dataset/Vitiligo DS/vitiligo"

normal_path = "dataset/Vitiligo DS/Healthy Skin"

print("Vitiligo Images:",
      len(os.listdir(vitiligo_path)))

print("Healthy Skin Images:",
      len(os.listdir(normal_path)))

"""Image Preprocessing Function"""

def preprocess_image(image_path):

    img = cv2.imread(image_path)

    img = cv2.resize(img, (224,224))

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    blur = cv2.GaussianBlur(gray, (5,5), 0)

    return img, gray, blur

"""Show Preprocessing Result"""

sample_image = os.path.join(vitiligo_path,
                            os.listdir(vitiligo_path)[0])

img, gray, blur = preprocess_image(sample_image)

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original")

plt.subplot(1,3,2)
plt.imshow(gray, cmap='gray')
plt.title("Gray")

plt.subplot(1,3,3)
plt.imshow(blur, cmap='gray')
plt.title("Blur")

plt.show()

"""Segmentation"""

def segment_image(blur):

    ret, thresh = cv2.threshold(
        blur,
        180,
        255,
        cv2.THRESH_BINARY_INV
    )

    return thresh

"""Show Segmentation"""

segmented = segment_image(blur)

plt.imshow(segmented, cmap='gray')
plt.title("Segmented Image")
plt.show()

"""Feature Extraction"""

def extract_features(image):

    white_pixels = np.sum(image > 200)

    total_pixels = image.shape[0] * image.shape[1]

    white_ratio = white_pixels / total_pixels

    mean = np.mean(image)

    std = np.std(image)

    return [white_ratio, mean, std]

"""Prepare Dataset"""

X = []
y = []

# Vitiligo Images
for file in os.listdir(vitiligo_path):

    path = os.path.join(vitiligo_path, file)

    img, gray, blur = preprocess_image(path)

    segmented = segment_image(blur)
    features = extract_features(segmented)

    X.append(features)

    y.append(1)

# Normal Images
for file in os.listdir(normal_path):

    path = os.path.join(normal_path, file)

    img, gray, blur = preprocess_image(path)

    segmented = segment_image(blur)

    features = extract_features(segmented)

    X.append(features)

    y.append(0)

X = np.array(X)
y = np.array(y)

print("Dataset Ready")

"""Split Dataset"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Train KNN Model"""

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X_train, y_train)

print("Model Trained")

"""Prediction"""

y_pred = model.predict(X_test)

"""Accuracy"""

acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc * 100)

"""Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,5))

sns.heatmap(cm, annot=True, fmt='d')

plt.title("Confusion Matrix")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""Precision Recall F1"""

print(classification_report(y_test, y_pred))

"""Test Your Own Image"""

from google.colab import files

uploaded = files.upload()

"""Predict Uploaded Image"""

test_image = "skin2.jpg"

img, gray, blur = preprocess_image(test_image)

segmented = segment_image(blur)

features = extract_features(segmented)

prediction = model.predict([features])

plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Test Image")
plt.show()

if prediction == 1:
    print("Vitiligo Detected")

else:
    print("Healthy Skin")

import pickle

pickle.dump(model, open("vitiligo_model.pkl", "wb"))

print("Model Saved")